server:
  port: 8081

spring:
  application:
    name: weather-city-data

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true # 以IP的形式注册到服务发现，默认是主机名
    #ip-address: 127.0.0.1 # 指定注入的ip地址
