server:
  port: 8091
spring:
  application:
    name: weather-data
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
weather-city-data:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 使用随机策略，默认是轮询

feign:
  hystrix:
    enabled: true

